### ISSUE TITLE
No folder available

### ISSUE THREAD

**Issue by matthijs2704** [Djailla/nas-os-transmission#1]
Hi! I've just tried to compile this for my Personal Cloud, and it went all well (it installed like a charm). But now I'm stuck with this "setup" screen which just says "No folder available"

Any idea how to make it work?

**Comment by Djailla** [comment]
Hello @matthijs2704 

I have some upcoming commit to fix this. Stay tuned ;)

**Comment by Djailla** [comment]
@matthijs2704 commit pushed, if you want a ready package feel free to ask ;) And if you want to contribute, help is welcomed.

**Comment by matthijs2704** [comment]
Awesome! Thanks @Djailla for the quick commit :) Could you send me the ready package? Is easier than booting that VM again 😜

**Comment by Djailla** [comment]
Can you try this :

https://drive.google.com/file/d/0B7dce31aFz-LdHV4YzcxTlA5dHc/view?usp=sharing

And let me know ?

**Comment by hiagocosta** [comment]
> Can you try this :
> 
> https://drive.google.com/file/d/0B7dce31aFz-LdHV4YzcxTlA5dHc/view?usp=sharing
> 
> And let me know ?

can you share it again?
it asked for access in that link
