### ISSUE TITLE
Does not compile on current SDK version

### ISSUE THREAD

**Issue by jadomski** [Djailla/nas-os-transmission#2]
Getting the following error when attempting to compile on Seagate current NAS OS SDK (version 0.7)

`Error : Error missing dependancy org.debian.jessie-lamp-1.0`

**Comment by nascob** [comment]
That's not the project. The NAS OS SDK needs internet connectivity in your VM to download the dependencies (i.e. `org.debian.jessie-lamp-1.0`). Are you sure you can access the internet?

**Comment by jadomski** [comment]
The VM can definitely connect to the internet, I downloaded the git project from within the VM and can run an OS update successfully too.

**Comment by nascob** [comment]
Good. Did you try running the build from the terminal? Is that the only error that you're getting?

**Comment by jadomski** [comment]
I just tried running it from the terminal and get the same error.

```
rainbow@rainbow:~$ sudo rainbow --build com.transmisisonbt.transmission --arch=x86_64
[ERROR] Error missing dependency org.debian.jessie-lamp-1.0
rainbow@rainbow:~$
```

**Comment by SUPERHAMSTERI** [comment]
Just change depends @ package.json to com.ubuntu.trusty-lamp-1.0

**Comment by jadomski** [comment]
That works but gives me an old version of Transmission...

**Comment by Djailla** [comment]
You can try to run 

`sudo do-release-upgrade`

In the build.sh script. This will upgrade Ubuntu and allow you to install the latest version of Transmission

**Comment by jackxujh** [comment]
So the NAS OS has been able to install apps from Ubuntu repo for the whole time?!

**Comment by Djailla** [comment]
In the build script yes !

**Comment by jackxujh** [comment]
Oh cool! I will try that as soon as my Personal Cloud is returned from *data recovery*. 😂😂

**Comment by jadomski** [comment]
> You can try to run
> 
> `sudo do-release-upgrade`
> 
> In the build.sh script.

Unfortunately this does not work, and fails with apt error. I've pretty much given up on Seagate's woeful SDK at this point in time.

**Comment by radziuxd** [comment]
Please, can someone upload already compiled .rbw file with new Transmission version?
